version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
